import { Inter } from "next/font/google";

// theme
import ThemeProvider from "./theme";
import ReduxStoreProvider from "./ReduxStoreProvider";

import AuthProvider from "./auth/JwtContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxStoreProvider>
          <AuthProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </AuthProvider>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
