// ********** AUTH **********
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const INITIAL = "INITIAL";
export const INITIALIZE_SESSION = "INITIALIZE_SESSION";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";

// ********** CAR **********
export const GET_CAR_REQUEST = "GET_CAR_REQUEST";
export const GET_CAR_SUCCESS = "GET_CAR_SUCCESS";
export const GET_CAR_BY_ID_REQUEST = "GET_CAR_BY_ID_REQUEST";
export const GET_CAR_BY_ID_SUCCESS = "GET_CAR_BY_ID_SUCCESS";
export const CREATE_CAR_REQUEST = "CREATE_CAR_REQUEST";
export const CREATE_CAR_SUCCESS = "CREATE_CAR_SUCCESS";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const CAR_ERROR = "CAR_ERROR";
export const CLEAR_CAR_LIST = "CLEAR_CAR_LIST";
export const CLEAR_CAR = "CLEAR_CAR";

// ********** ERROR & MESSAGE **********
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const CLEAR_ERROR = "CLEAR_ERROR";
